# Generated by Django 3.1.1 on 2020-09-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('image', models.ImageField(upload_to='article/', verbose_name='Gambar')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='buat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ubah')),
            ],
        ),
    ]
